#! /bin/sh


test $# -ge 2 || {
	echo "usage: enter [args] img cmd [args]"
	exit 1
}

docker run \
	-it \
	--rm \
	-e DISPLAY \
	-u $(id -u) \
	--net=host \
	-v /etc/localtime:/etc/localtime:ro \
	-v /tmp/.X11-unix \
	"$@"
